nelmio_api_doc:
    documentation:
        info:
            title: BileMo
            description: BileMo API which provide useful informations for its customers. 
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    models: { use_jms: false }
