nelmio_api_doc:
    documentation:
        info:
            title: BileMo
            description: BileMo is an API service which provide useful informations for its customers. 
            version: 1.0.0
        components:
            parameters:
                id:
                    name: "id"
                    description: "The ressource id"
                    in: "path"
                    required: true
                    schema:
                        type: integer

        # security:
        #     - Bearer: ['123']
    areas:
        path_patterns: # an array of regexps
            - ^/api(?!/doc$)
        # host_patterns:
        #     - ^api\.